/* Auto-generated by genmsg_cpp for file /home/sahabi/ws/sandbox/quad_control/msg/Pose.msg */
#ifndef QUAD_CONTROL_MESSAGE_POSE_H
#define QUAD_CONTROL_MESSAGE_POSE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "quad_control/Point.h"
#include "quad_control/Quaternion.h"

namespace quad_control
{
template <class ContainerAllocator>
struct Pose_ {
  typedef Pose_<ContainerAllocator> Type;

  Pose_()
  : position()
  , orientation()
  {
  }

  Pose_(const ContainerAllocator& _alloc)
  : position(_alloc)
  , orientation(_alloc)
  {
  }

  typedef  ::quad_control::Point_<ContainerAllocator>  _position_type;
   ::quad_control::Point_<ContainerAllocator>  position;

  typedef  ::quad_control::Quaternion_<ContainerAllocator>  _orientation_type;
   ::quad_control::Quaternion_<ContainerAllocator>  orientation;


  typedef boost::shared_ptr< ::quad_control::Pose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quad_control::Pose_<ContainerAllocator>  const> ConstPtr;
}; // struct Pose
typedef  ::quad_control::Pose_<std::allocator<void> > Pose;

typedef boost::shared_ptr< ::quad_control::Pose> PosePtr;
typedef boost::shared_ptr< ::quad_control::Pose const> PoseConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::quad_control::Pose_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::quad_control::Pose_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace quad_control

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::quad_control::Pose_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::quad_control::Pose_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::quad_control::Pose_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e45d45a5a1ce597b249e23fb30fc871f";
  }

  static const char* value(const  ::quad_control::Pose_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xe45d45a5a1ce597bULL;
  static const uint64_t static_value2 = 0x249e23fb30fc871fULL;
};

template<class ContainerAllocator>
struct DataType< ::quad_control::Pose_<ContainerAllocator> > {
  static const char* value() 
  {
    return "quad_control/Pose";
  }

  static const char* value(const  ::quad_control::Pose_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::quad_control::Pose_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
================================================================================\n\
MSG: quad_control/Point\n\
float64 x\n\
float64 y\n\
float64 z\n\
================================================================================\n\
MSG: quad_control/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const  ::quad_control::Pose_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::quad_control::Pose_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::quad_control::Pose_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.position);
    stream.next(m.orientation);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Pose_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quad_control::Pose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::quad_control::Pose_<ContainerAllocator> & v) 
  {
    s << indent << "position: ";
s << std::endl;
    Printer< ::quad_control::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "orientation: ";
s << std::endl;
    Printer< ::quad_control::Quaternion_<ContainerAllocator> >::stream(s, indent + "  ", v.orientation);
  }
};


} // namespace message_operations
} // namespace ros

#endif // QUAD_CONTROL_MESSAGE_POSE_H

