/* Auto-generated by genmsg_cpp for file /home/sahabi/ws/sandbox/quad_control/msg/Quaternion.msg */
#ifndef QUAD_CONTROL_MESSAGE_QUATERNION_H
#define QUAD_CONTROL_MESSAGE_QUATERNION_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace quad_control
{
template <class ContainerAllocator>
struct Quaternion_ {
  typedef Quaternion_<ContainerAllocator> Type;

  Quaternion_()
  : x(0.0)
  , y(0.0)
  , z(0.0)
  , w(0.0)
  {
  }

  Quaternion_(const ContainerAllocator& _alloc)
  : x(0.0)
  , y(0.0)
  , z(0.0)
  , w(0.0)
  {
  }

  typedef double _x_type;
  double x;

  typedef double _y_type;
  double y;

  typedef double _z_type;
  double z;

  typedef double _w_type;
  double w;


  typedef boost::shared_ptr< ::quad_control::Quaternion_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quad_control::Quaternion_<ContainerAllocator>  const> ConstPtr;
}; // struct Quaternion
typedef  ::quad_control::Quaternion_<std::allocator<void> > Quaternion;

typedef boost::shared_ptr< ::quad_control::Quaternion> QuaternionPtr;
typedef boost::shared_ptr< ::quad_control::Quaternion const> QuaternionConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::quad_control::Quaternion_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::quad_control::Quaternion_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace quad_control

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::quad_control::Quaternion_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::quad_control::Quaternion_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::quad_control::Quaternion_<ContainerAllocator> > {
  static const char* value() 
  {
    return "a779879fadf0160734f906b8c19c7004";
  }

  static const char* value(const  ::quad_control::Quaternion_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xa779879fadf01607ULL;
  static const uint64_t static_value2 = 0x34f906b8c19c7004ULL;
};

template<class ContainerAllocator>
struct DataType< ::quad_control::Quaternion_<ContainerAllocator> > {
  static const char* value() 
  {
    return "quad_control/Quaternion";
  }

  static const char* value(const  ::quad_control::Quaternion_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::quad_control::Quaternion_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const  ::quad_control::Quaternion_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::quad_control::Quaternion_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::quad_control::Quaternion_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.z);
    stream.next(m.w);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Quaternion_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quad_control::Quaternion_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::quad_control::Quaternion_<ContainerAllocator> & v) 
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "w: ";
    Printer<double>::stream(s, indent + "  ", v.w);
  }
};


} // namespace message_operations
} // namespace ros

#endif // QUAD_CONTROL_MESSAGE_QUATERNION_H

