/* Auto-generated by genmsg_cpp for file /home/sahabi/ws/sandbox/quad_control/msg/Vector3.msg */
#ifndef QUAD_CONTROL_MESSAGE_VECTOR3_H
#define QUAD_CONTROL_MESSAGE_VECTOR3_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace quad_control
{
template <class ContainerAllocator>
struct Vector3_ {
  typedef Vector3_<ContainerAllocator> Type;

  Vector3_()
  : x(0.0)
  , y(0.0)
  , z(0.0)
  {
  }

  Vector3_(const ContainerAllocator& _alloc)
  : x(0.0)
  , y(0.0)
  , z(0.0)
  {
  }

  typedef double _x_type;
  double x;

  typedef double _y_type;
  double y;

  typedef double _z_type;
  double z;


  typedef boost::shared_ptr< ::quad_control::Vector3_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quad_control::Vector3_<ContainerAllocator>  const> ConstPtr;
}; // struct Vector3
typedef  ::quad_control::Vector3_<std::allocator<void> > Vector3;

typedef boost::shared_ptr< ::quad_control::Vector3> Vector3Ptr;
typedef boost::shared_ptr< ::quad_control::Vector3 const> Vector3ConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::quad_control::Vector3_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::quad_control::Vector3_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace quad_control

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::quad_control::Vector3_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::quad_control::Vector3_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::quad_control::Vector3_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4a842b65f413084dc2b10fb484ea7f17";
  }

  static const char* value(const  ::quad_control::Vector3_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x4a842b65f413084dULL;
  static const uint64_t static_value2 = 0xc2b10fb484ea7f17ULL;
};

template<class ContainerAllocator>
struct DataType< ::quad_control::Vector3_<ContainerAllocator> > {
  static const char* value() 
  {
    return "quad_control/Vector3";
  }

  static const char* value(const  ::quad_control::Vector3_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::quad_control::Vector3_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const  ::quad_control::Vector3_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::quad_control::Vector3_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::quad_control::Vector3_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.z);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Vector3_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quad_control::Vector3_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::quad_control::Vector3_<ContainerAllocator> & v) 
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
  }
};


} // namespace message_operations
} // namespace ros

#endif // QUAD_CONTROL_MESSAGE_VECTOR3_H

